# age1xtrdxzsnl88w8su43sk2nt02t4vmmaa2hpq9a2mancq9axzmnp8sd2tyyh: GH Actions Runner
creation_rules:
  - age: >-
      age1a5c726yqajxf635dtvkt5pfydfg9mjf72dn458u53arjx3g5tphsxa3u3w,
      age1xtrdxzsnl88w8su43sk2nt02t4vmmaa2hpq9a2mancq9axzmnp8sd2tyyh